### ISSUE TITLE
Wrong validation of card numbers out of Int range

### ISSUE THREAD

**Issue by janjelinek** [ersocon/creditcard-validation#4]
As you can see here https://www.freeformatter.com/credit-card-number-generator-validator.html
Card number should be 19 digits long. So when you have used `Int` type for card number, you are able to validate max numbers about integer maximum (~ 9007 1992 5474 0992).

I can prepare PR with fix (maybe during last week) but it will be BC break because of `isValid` current paramenter `Int`.

**Comment by ersocon** [comment]
Thank you! Yes, of course, any PR is welcome. I don't see any problem to release the new version as 2.0
